# Generated by Django 4.0.2 on 2022-02-22 01:25

from django.db import migrations, models
import django.db.models.deletion
import rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(models.Model, rest.models.RestModel),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=124)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.group')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.member')),
            ],
            bases=(models.Model, rest.models.RestModel),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('transport', models.CharField(blank=True, default=None, max_length=124, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_settings', to='account.member')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notify.topic')),
            ],
            bases=(models.Model, rest.models.RestModel),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('service', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('platform', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('hw_version', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('os_version', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('rid', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.member')),
            ],
            bases=(models.Model, rest.models.RestModel),
        ),
    ]
