# Generated by Django 4.0.2 on 2022-02-22 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialib', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='Profile picture', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='medialib.mediaitem'),
        ),
    ]
